title: Lionel Kirrmann
email: #
description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: https://lionelkirrmann.com
asset_url: /assets

google_analytics:

future: true # Show blog post of future date
permalink: /blogs/:year/:month/:day/:title/

sass:
  style: compressed

# Build settings
markdown: kramdown

exclude:
  - .DS_Store
  - README.md
